# This is a basic workflow to help you get started with Actions

name: Pull Request Check

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # setup env
      - name: setup env
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt

      # Run linting
      - name: run linting
        run: flake8 --config=setup.cfg 

      # Run black
      - name: run black
        run: black --verbose

      # Run isort
      - name: run isort
        run: isort

      # Runs a set of commands using the runners shell
      - name: Run pytests
        run: python -m pytest
